### ISSUE TITLE
adding lcov tracefile failed with Error : ValueError: invalid literal for int() with base 10: '-'

### ISSUE THREAD

**Issue by rachit16** [RPGillespie6/fastcov#88]
While Adding 2 tracefiles generated with gcov ( gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 ) I am facing below error 

[0.007s] [info]: Performing combine operation
Traceback (most recent call last):
  File "/usr/local/bin/fastcov", line 1004, in <module>
    main()
  File "/usr/local/bin/fastcov", line 975, in main
    fastcov_json = getCombineCoverage(args)
  File "/usr/local/bin/fastcov", line 807, in getCombineCoverage
    fastcov_json = parseAndCombine(args.combine)
  File "/usr/local/bin/fastcov", line 787, in parseAndCombine
    report = parseInfo(path)
  File "/usr/local/bin/fastcov", line 768, in parseInfo
    current_data["branches"][line_num].append(int(count))
ValueError: invalid literal for int() with base 10: '-'

Command Executed : fastcov -C test1.info test2.info --lcov -o result.info

**Comment by RPGillespie6** [comment]
Could you provide a copy of whichever info file has a hyphen in it (either `test1.info` or `test2.info`) I haven't encounted a case before where a .info file has hyphens instead of numerical values.

**Comment by rachit16** [comment]
File is too big to be shared , i can share few lines where BRDA tag have hypens and values both at the end.
BRDA:307,0,1,-
BRDA:310,0,0,0
BRDA:310,0,1,0
BRDA:320,0,0,-
BRDA:320,0,1,-

**Comment by RPGillespie6** [comment]
This is good enough. Hmm, I'm not sure exactly what the difference between `-` and `0` is, I'm going to check with lcov's maintainers really quick. In all likelihood I think hyphen can be treated like zero and I can put in a fix. In the meantime, you can preprocess your info file to replace `BRDA:*,-` with `BRDA*,0`

**Comment by rachit16** [comment]
Sure thanks , will make the changes as suggested.

**Comment by RPGillespie6** [comment]
This should be fixed now
