### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'NaN'

### ISSUE THREAD

**Issue by StanKatsyuk-at** [RPGillespie6/fastcov#93]
When I merge coverage for many lcov.info reports generated via `nyc`, I get a failure with stacktrace
```Traceback (most recent call last):
  File "/Users/stanislav.katsyuk/h/node/env-16.17.0/bin/fastcov", line 1004, in <module>
    main()
  File "/Users/stanislav.katsyuk/h/node/env-16.17.0/bin/fastcov", line 975, in main
    fastcov_json = getCombineCoverage(args)
  File "/Users/stanislav.katsyuk/h/node/env-16.17.0/bin/fastcov", line 807, in getCombineCoverage
    fastcov_json = parseAndCombine(args.combine)
  File "/Users/stanislav.katsyuk/h/node/env-16.17.0/bin/fastcov", line 787, in parseAndCombine
    report = parseInfo(path)
  File "/Users/stanislav.katsyuk/h/node/env-16.17.0/bin/fastcov", line 768, in parseInfo
    current_data["branches"][line_num].append(int(count))
ValueError: invalid literal for int() with base 10: 'NaN'
```
I believe I found the file in question and it shows the following two lines with `NaN`'s

```
BRDA:78,6,2,NaN
```
and
```
BRDA:215,18,1,NaN
```

**Comment by StanKatsyuk-at** [comment]
When running lcov on the same set of `lcov.info` files, I don't get a failure to merge but do get warnings possibly related to the same sourcefile 

```
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
lcov: WARNING: function data mismatch at <redacted>
```

**Comment by RPGillespie6** [comment]
Ah, `nyc` must be storing that value as a floating point type which is then somehow being serialized to `NaN`. Should be easy enough to handle, let me take a look

**Comment by RPGillespie6** [comment]
@StanKatsyuk-at Could you verify the latest fastcov.py on master fixes the issue for you?

**Comment by StanKatsyuk-at** [comment]
Looks like its displaying a warning but merging continues as expected
```
[0.013s] [warning]: Unsupported numerical value 'NaN', using 0
[0.000s] [warning]: Unsupported numerical value 'NaN', using 0
```

Thanks for the quick patch @RPGillespie6!
